Insert into storage(storage_id,name) values(1,'MTSDS');
Insert into section(section_id,category_id,free_positions,store_id) values(1,1,25,1);
Insert into section(section_id,category_id,free_positions,store_id) values(2,2,25,1);
Insert into section(section_id,category_id,free_positions,store_id) values(3,3,25,1);
Insert into section(section_id,category_id,free_positions,store_id) values(4,4,25,1);
Insert into section(section_id,category_id,free_positions,store_id) values(5,5,25,1);
Insert into section(section_id,category_id,free_positions,store_id) values(6,6,25,1);
Insert into section(section_id,category_id,free_positions,store_id) values(7,7,25,1);
Insert into section(section_id,category_id,free_positions,store_id) values(8,8,25,1);